# Change these first
owner: minicraftserver # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: MiniCraft Server
    url: sv1xapp01-p.timschneider.info
    port: 25565
    check: "tcp-ping"
    ipv6: false
  - name: MiniCraft TeamSpeak
    url: sv1xapp01-p.timschneider.info
    port: 30033
    check: "tcp-ping"
    ipv6: false
  - name: MiniCraft Webseite
    url: https://minicraft-server.de
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Mojang Sessionserver
    url: https://sessionserver.mojang.com
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404
  - name: Mojang API Endpoints
    url: https://api.minecraftservices.com
    expectedStatusCodes:
      - 200
      - 201
      - 403
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.minicraft-server.de
  # baseUrl: /your-repo-name
  logoUrl: https://minicraft-server.de/images/logo/minicraft/logo.svg
  name: Minicraft Server Status
  introTitle: "Eine Statusseite über die Dienste von minicraft-server.de und Mojang"
  introMessage: Powered by [Upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Webseite
      href: https://minicraft-server.de
    - title: Forum
      href: https://minicraft-server.de/forum/
    - title: Twitter
      href: https://x.com/minicraftserver
    - title: Livemap
      href: https://livemap.minicraft-server.de      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
